### ISSUE TITLE
Quickbooks plugin status

### ISSUE THREAD

**Issue by davidojedalopez** [enrobsop/grails-quickbooks-online#1]
Hi!! I see this plugin is no longer maintained. Is it still usable for latest versions of the Quickbooks API?

**Comment by enrobsop** [comment]
Hi. The QuickBooks doc still lists [OAuth for connecting](https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/0085_develop_quickbooks_apps/0004_authentication_and_authorization/connect_from_within_your_app#/521) so the code should still work. I haven't tested it for a couple of years so I could be wrong! 

This plugin is also for Grails 2 and would need some work to migrate it to Grails 3.
